# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d5129db1f6b805d3a859384e320f7e7c4c7563ae8f4478917943c64276d991e076918216f6b625c325cc72e9587e56f2cae95fc414e2d55a5727c327ba9b45a

test:
  secret_key_base: 0710c3799f1c43a57f395f2d1fa84e24d223dd71c4e70e42911bca6df9e3811dd64bc83da24299dc0d276d917b0ab65dd0c41f4954c9573d5fad391748c2252c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
